### ISSUE TITLE
Dwarf Therapist gives error when attempting to start it

### ISSUE THREAD

**Issue by aalbaugh** [andrewd18/df-lnp-installer#20]
Hi, I just installed LNP on my Ubuntu Quantal (12.10) machine, and I get a large eror box whenever I try to start DwarfTherapist.

I saw the other similar issue, but I've turned pTrace protection off (and confirmed it is set to off) and this error is still happening.

here is the error message from the window.

java.lang.IllegalStateException: Error launching program.
    at nl.dricus.df.util.StartProcessUtil.executeCommandLine(StartProcessUtil.java:106)
    at nl.dricus.df.util.StartProcessUtilLinux.startProcess(StartProcessUtilLinux.java:46)
    at nl.dricus.df.state.LNP.startUtility(LNP.java:253)
    at nl.dricus.df.action.RunUtilityAction.actionPerformed(RunUtilityAction.java:39)
    at nl.dricus.df.form.main.UtilitiesGroup$UtilitiesListDoubleClickListener.mouseClicked(UtilitiesGroup.java:61)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6508)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.IOException: /home/adam/Downloads/dwarfFortressLNPlinux/df-lnp-installer/yes/LNP/utilities/dwarf_therapist doesn't exist.
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:181)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:170)
    at nl.dricus.df.util.StartProcessUtil.executeCommandLine(StartProcessUtil.java:90)
    ... 36 more

**Comment by andrewd18** [comment]
>  /home/adam/Downloads/dwarfFortressLNPlinux/df-lnp-installer/yes/LNP/utilities/dwarf_therapist doesn't exist.

**Comment by aalbaugh** [comment]
Why wouldn't it have installed along with LNP though?  Is there a way to re-install it after the fact?

edit: yeah, i have nothing about Therapist in the utilities folder.  hmmm...

**Comment by aalbaugh** [comment]
My apologies, I think I figured out how to resolve this.  I didn't have g++ installed when i installed LNP, and as you require g++ to 'make' Therapist, it didn't install.  I have since 'make'd Therapist, and moved the executable to the proper location.  Therapist runs, but doesn't connect to Dwarf Fortress at all.  But that is outside the scope for you i guess.

**Comment by andrewd18** [comment]
Sounds like the script needs a g++ dependency check. I thought that would have been implicitly pulled in as part of make but I guess not. I'll make the change.

Can you run through the steps in https://github.com/andrewd18/df-lnp-installer/issues/12 to see if that bug is happening to you? Version 0.3.0 will have an explicit check for it but 0.2.x doesn't right now.

**Comment by aalbaugh** [comment]
I've managed to get it working.  Turns out, i had both the issue from #12 and also the failure to install.

I ran into some trouble with the solutions/workarounds in #12 though, i'll make a post there shortly.

**Comment by andrewd18** [comment]
0.3.0 now has an explicit check for g++.
