### ISSUE TITLE
java exception when trying to change graphics

### ISSUE THREAD

**Issue by drfragment** [andrewd18/df-lnp-installer#5]
Log output:

java.lang.IllegalStateException: java.io.FileNotFoundException: Source '/home/me/bin/Dwarf Fortress/LNP/graphics/Phoebus_34_11v01/data/init/init.txt' does not exist
    at nl.dricus.df.action.InstallGraphicsPackAction.updateInitFiles(InstallGraphicsPackAction.java:112)
    at nl.dricus.df.action.InstallGraphicsPackAction.actionPerformed(InstallGraphicsPackAction.java:54)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.io.FileNotFoundException: Source '/home/me/bin/Dwarf Fortress/LNP/graphics/Phoebus_34_11v01/data/init/init.txt' does not exist
    at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
    at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
    at nl.dricus.df.action.InstallGraphicsPackAction.updateInitFiles(InstallGraphicsPackAction.java:108)
    ... 37 more

**Comment by andrewd18** [comment]
Confirmed in 0.1.2. It's an issue with the way Phoebus packaged his tileset zip. He's got a "phoebus" set of init files and a "phoebusnott" set, which I assume is no truetype.

Workaround: Copy files up where they belong. From your dwarf fortress folder, run:
cp LNP/graphics/Phoebus_34_11v01/data/init/phoebus/\* LNP/graphics/Phoebus_34_11v01/data/init/

**Comment by andrewd18** [comment]
Resolved in 0.1.3.
